---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: aws-fsx-csi-smb-driver
  name: fsx-csi-smb-controller-sa
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::864263594202:role/adept-dev-us-east-1-eks-fsx-csi-smb-driver-role ## Role arn of the EKS role that provides access to FSx